name: Check pull request
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_e2e_api:
    name: E2E test API
    # needs: [get-affected]
    strategy:
      # The order is important for ee to be first, otherwise outputs not work correctly
      matrix:
        name: ['novu/api-ee', 'novu/api']
    uses: ./.github/workflows/reusable-api-e2e.yml
    with:
      ee: ${{ contains (matrix.name,'-ee') }}
      test-e2e-affected: true
      test-e2e-ee-affected: true
      job-name: ${{ matrix.name }}
      test-unit: false
    secrets: inherit
